name: Generar Instalador Windows (.exe)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v4

    - name: Configurar Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Configurar Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Construir Shadow JAR
      run: ./gradlew shadowJar

    - name: Crear instalador con jpackage
      run: |
        jpackage `
          --name "ProyectoCocina" `
          --input build/libs/ `
          --main-jar ProyectoCocina-1.0-all.jar `
          --main-class org.proyectococina.Launcher `
          --type exe `
          --win-shortcut `
          --win-menu `
          --icon src/main/resources/icon.ico

    - name: Subir el instalador (.exe)
      uses: actions/upload-artifact@v4
      with:
        name: Instalador-Windows
        path: "*.exe"